### ISSUE TITLE
Package deps may be out of date

### ISSUE THREAD

**Issue by NatElkins** [Zaid-Ajaj/fable-getting-started#6]
Just cloned this repo while starting to follow https://zaid-ajaj.github.io/the-elmish-book/ .  Upon running `npm install`, I got the following errors:

![image](https://user-images.githubusercontent.com/1795462/81478494-f01d1000-91eb-11ea-96f2-9b352f277be2.png)

Removing node_modules, package-lock.json, and running `npm install` again resolved my issues, although I got this warning:

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/1795462/81478526-1a6ecd80-91ec-11ea-8512-b5ad0f4d3452.png">

Just wanted to give a heads up.  Don't know the ecosystem well enough to know if simply updating the dependencies is enough to fix this, but it worked for me.

**Comment by Zaid-Ajaj** [comment]
Will be fixed by #31
